### PR TITLE
implement HipChat notifications

### PR DESCRIPTION
**Pull request by Elhebert**
Hi,

Here's the HipChat notification implementation. 

I'm not using HipChat, so I can't really test this, but if I trust the documentation and the source code of the HipChat directive, this implementation should work without any problems.

### CODE REVIEW

**Comment by Elhebert** [comment]
Just tried to deploy something,  and the `@hipchat` directive isn't "parsed" by Envoy 🤔  Gonna have to look into this, so... wait before merging 😄

**Comment by mattiasgeniar** [comment]
👍 

Nice work!

**Comment by Elhebert** [comment]
@mattiasgeniar As stated in my comment above (we might have done it at the same time), there's an issue with the `@hipchat` directive.

Envoy isn't parsing it to call the webhook. It just return the directive, which result in an error.

**Comment by mattiasgeniar** [comment]
Ah, was just assuming that would work. :-)

Slack has always had first-party support in Laravel, Hipchat not so much. Might be too much of a hassle to implement though.

**Comment by Elhebert** [comment]
Well, I was assuming the same thing.

I did used the Envoy repo as "documentation", and there's a [HipChat](https://github.com/laravel/envoy/blob/master/src/Hipchat.php) class, and you can find reference to HipChat in it's compiler: https://github.com/laravel/envoy/blob/master/src/Compiler.php#L405-L416

Also in early version of Laravel 5 (up to 5.2), there's a mention of HipChat in the Envoy documentation.

So, it's pretty weird... Since Envoy doesn't accept issues I'm going to open an issue in the Laravel/framework repo about it.

**Pull request merged**
